apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision: 1.29.0
    chart: nginx-ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
