resources:
- base/argo-ui-ingress.yaml
- base/argo-ci-ingress.yaml
- base/argo-ci-cm.yaml

bases:
- github.com/argoproj/argo//manifests/cluster-install
- github.com/argoproj/argo-ci//manifests?ref=manifests

patchesStrategicMerge:
- overlays/production/argo-ci-deployment.yaml
- overlays/production/workflow-controller-config-map.yaml

imageTags:
- name: argoproj/argoui
  newTag: v2.2.1-2539322
- name: argoproj/argoexec
  newTag: v2.2.1
- name: argoproj/workflow-controller
  newTag: v2.2.1
- name: argoproj/argoci
  newTag: v0.0.1-701df82
namespace: argoci
