apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-ui
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/app-root: "/"
spec:
  tls:
  - hosts:
    - ci.apps.argoproj.io
  rules:
  - host: ci.apps.argoproj.io
    http:
      paths:
      - path: /
        backend:
          serviceName: argo-ui
          servicePort: 80
